#! /bin/bash

input=""
counter=0
cmd=""
confirmation=false

commandWrapper() {
	pass=false
        echo -e "\n[Script] Step: $counter \?Command: $cmd\n"
	if [ "$confirmation" == true ]; then
		while [ "$pass" == false ]
		do
			read -n 1 -p "[Script] Proceed? [Y/n] " input
			if [[ "$input" == "Y" || "$input" == "y" || "$input" == "" ]]; then
				pass=true
				continue
			elif [[ "$input" == "N" || "$input" == "n" ]]; then
				exit
			else
				continue
			fi
		done
	fi
	pass=false
	bash "$cmd"
	counter=$((counter+1))
	sleep 0.5	
}

cmd='echo "Hello world!"'
commandWrapper
